# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ei.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


class Platform(betterproto.Enum):
    _ = 0
    IOS = 1
    DROID = 2


class EggIncFirstContactResponseErrorCodes(betterproto.Enum):
    NO_ERROR = 0
    EXISTING_USER_W_GAMER_ID = 1
    USER_NOT_FOUND = 2
    BACKUP_CONFLICT = 3


class MissionInfoSpaceship(betterproto.Enum):
    CHICKEN_ONE = 0
    CHICKEN_NINE = 1
    CHICKEN_HEAVY = 2
    BCR = 3
    MILLENIUM_CHICKEN = 4
    CORELLIHEN_CORVETTE = 5
    GALEGGTICA = 6
    CHICKFIANT = 7
    VOYEGGER = 8
    HENERPRISE = 9
    ATREGGIES = 10


class MissionInfoDurationType(betterproto.Enum):
    SHORT = 0
    LONG = 1
    EPIC = 2
    TUTORIAL = 3


class ArtifactSpecName(betterproto.Enum):
    LUNAR_TOTEM = 0
    NEODYMIUM_MEDALLION = 3
    BEAK_OF_MIDAS = 4
    LIGHT_OF_EGGENDIL = 5
    DEMETERS_NECKLACE = 6
    VIAL_MARTIAN_DUST = 7
    ORNATE_GUSSET = 8
    THE_CHALICE = 9
    BOOK_OF_BASAN = 10
    PHOENIX_FEATHER = 11
    TUNGSTEN_ANKH = 12
    AURELIAN_BROOCH = 21
    CARVED_RAINSTICK = 22
    PUZZLE_CUBE = 23
    QUANTUM_METRONOME = 24
    SHIP_IN_A_BOTTLE = 25
    TACHYON_DEFLECTOR = 26
    INTERSTELLAR_COMPASS = 27
    DILITHIUM_MONOCLE = 28
    TITANIUM_ACTUATOR = 29
    MERCURYS_LENS = 30
    TACHYON_STONE = 1
    DILITHIUM_STONE = 31
    SHELL_STONE = 32
    LUNAR_STONE = 33
    SOUL_STONE = 34
    PROPHECY_STONE = 39
    QUANTUM_STONE = 36
    TERRA_STONE = 37
    LIFE_STONE = 38
    CLARITY_STONE = 40
    EXTRATERRESTRIAL_ALUMINUM = 13
    ANCIENT_TUNGSTEN = 14
    SPACE_ROCKS = 15
    ALIEN_WOOD = 16
    GOLD_METEORITE = 17
    TAU_CETI_GEODE = 18
    CENTAURIAN_STEEL = 19
    ERIDANI_FEATHER = 20
    DRONE_PARTS = 35
    CELESTIAL_BRONZE = 41
    LALANDE_HIDE = 42
    SOLAR_TITANIUM = 43
    TACHYON_STONE_FRAGMENT = 2
    DILITHIUM_STONE_FRAGMENT = 44
    SHELL_STONE_FRAGMENT = 45
    LUNAR_STONE_FRAGMENT = 46
    SOUL_STONE_FRAGMENT = 47
    PROPHECY_STONE_FRAGMENT = 48
    QUANTUM_STONE_FRAGMENT = 49
    TERRA_STONE_FRAGMENT = 50
    LIFE_STONE_FRAGMENT = 51
    CLARITY_STONE_FRAGMENT = 52
    UNKNOWN = 10000


class ArtifactSpecLevel(betterproto.Enum):
    INFERIOR = 0
    LESSER = 1
    NORMAL = 2
    GREATER = 3
    SUPERIOR = 4


class ArtifactSpecRarity(betterproto.Enum):
    COMMON = 0
    RARE = 1
    EPIC = 2
    LEGENDARY = 3


class ArtifactSpecType(betterproto.Enum):
    ARTIFACT = 0
    STONE = 1
    INGREDIENT = 2
    STONE_INGREDIENT = 3


@dataclass(eq=False, repr=False)
class BasicRequestInfo(betterproto.Message):
    ei_user_id: str = betterproto.string_field(1)
    client_version: int = betterproto.uint32_field(2)
    version: str = betterproto.string_field(3)
    build: str = betterproto.string_field(4)
    platform: str = betterproto.string_field(5)
    country: str = betterproto.string_field(6)
    language: str = betterproto.string_field(7)
    debug: bool = betterproto.bool_field(8)


@dataclass(eq=False, repr=False)
class AuthenticatedMessage(betterproto.Message):
    message: bytes = betterproto.bytes_field(1)
    version: int = betterproto.uint32_field(3)
    code: str = betterproto.string_field(2)
    compressed: bool = betterproto.bool_field(4)
    original_size: int = betterproto.uint32_field(5)
    user_id: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class EggIncFirstContactRequest(betterproto.Message):
    rinfo: "BasicRequestInfo" = betterproto.message_field(8)
    ei_user_id: str = betterproto.string_field(4)
    user_id: str = betterproto.string_field(1)
    game_services_id: str = betterproto.string_field(7)
    device_id: str = betterproto.string_field(5)
    username: str = betterproto.string_field(6)
    client_version: int = betterproto.uint32_field(2)
    platform: "Platform" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class EggIncFirstContactResponse(betterproto.Message):
    ei_user_id: str = betterproto.string_field(2)
    ids_transferred: List[str] = betterproto.string_field(3)
    error_code: int = betterproto.uint32_field(4)
    error_message: str = betterproto.string_field(5)
    backup: "Backup" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class MissionInfo(betterproto.Message):
    ship: "MissionInfoSpaceship" = betterproto.enum_field(1)
    duration_type: "MissionInfoDurationType" = betterproto.enum_field(3)
    level: int = betterproto.uint32_field(12)
    identifier: bytes = betterproto.bytes_field(7)


@dataclass(eq=False, repr=False)
class ArtifactSpec(betterproto.Message):
    name: "ArtifactSpecName" = betterproto.enum_field(1)
    level: "ArtifactSpecLevel" = betterproto.enum_field(2)
    rarity: "ArtifactSpecRarity" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class CompleteArtifact(betterproto.Message):
    spec: "ArtifactSpec" = betterproto.message_field(1)
    stones: List["ArtifactSpec"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ArtifactInventoryItem(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    artifact: "CompleteArtifact" = betterproto.message_field(2)
    quantity: float = betterproto.double_field(3)
    server_id: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ArtifactsDb(betterproto.Message):
    inventory_items: List["ArtifactInventoryItem"] = betterproto.message_field(1)
    fueling_mission: "MissionInfo" = betterproto.message_field(14)
    mission_infos: List["MissionInfo"] = betterproto.message_field(4)
    mission_archive: List["MissionInfo"] = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class Backup(betterproto.Message):
    ei_user_id: str = betterproto.string_field(18)
    artifacts_db: "ArtifactsDb" = betterproto.message_field(15)
